### ISSUE TITLE
How does this method compared against non learning based one??

### ISSUE THREAD

**Issue by LeLocTai** [hbertiche/NeuralClothSim#2]
In the paper there are comparison against existing learning based method. But how does it compared against existing real time approach like XPBD?

As a side note, it is rather odd that you are using FPS as a performance measure. In real time application we usually want a frame time to fit into existing budget. I'm assuming your FPS measure did not exclude the time for other things, such as rendering or animation?

**Comment by hbertiche** [comment]
thanks for your interest in my work!

comparison with physically based simulation (PBS) is an interesting but complex topic,
simulation complexity can be increased or reduced to adapt to the application requirements, with its corresponding impact on the results,
additionally, in simulations there are other things to consider, such as the number and complexity of colliders and other external factors,
because of this, it is not straightforward to find a universal benchmark to compare with simulation,

in our paper, we report the performance measured from the raw pose data (as quaternions) to the output body and garment meshes, so character animation is included in this measurement,
we obtain faster than real-time performance for garments up to 80k vertices,
another interesting difference wrt simulation is that, at inference time, the number of vertices of the body (the collider) has no impact in the performance, that is, the complexity of the network is O(n), where 'n' is the number of vertices in the cloth,
also note how neural networks are efficiently parallelizable in a GPU,
the size of the model is usually in the order of a few megabytes, which leaves plenty of room for many processes running in parallel,
another interesting property is that learnt approaches are more stable and can start at arbitrary poses,
on the other hand, it is worth noting that PBS can handle _any_ scenario, so in the end, it is a tradeoff between performance and generalization

while we report performance in FPS, it is possible to obtain frame time by inverting this value,
rendering times cannot be considered in the measurements, since its cost will greatly depend on many factors, and thus, it would not be a reliable measure,

it is also important to mention this is a research project, and it is therefore quite likely that this approach could be further optimized with the valuable work of experienced software engineers
